/*
 * NewJInternalFramee.java
 *
 * Created on __DATE__, __TIME__
 */

package NewClient;

import java.awt.Dimension;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

import sfs2x.client.entities.Room;
import sfs2x.client.example.ChildRummyBot;
import sfs2x.client.example.RummyBot;
import sfs2x.client.example.UserTurnTimer;
import BotLogin.RequestIniatiator;

/**
 *
 * @author  vaibhav
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {

	String roomName = "";
	String multiplier = "";
	int botId = 0;
	Room roomObject = null;
	RummyBot rummyGlobalObj = null;
	RequestIniatiator reqinitGlobalObj = null;
	ChildRummyBot childRummyGlobalObj = null;
	UserTurnTimer turnTimerObj = null;

	/** Creates new form NewJInternalFramee */
	public NewJInternalFrame() {
		initComponents();

		jTextArea1.setEditable(false);
		jTextArea1.setFocusable(false);
		jTextArea2.setEditable(false);
		jTextArea2.setFocusable(false);
		this.getRootPane().setDefaultButton(jButton1);

		//        this.addComponentListener(new ComponentAdapter() {
		//        public void componentResized(ComponentEvent ce)
		//        {
		//          
		//        }
		//        });

		iconable = true;
		this.addInternalFrameListener(new InternalFrameAdapter() {
			@Override
			public void internalFrameIconified(InternalFrameEvent ie) {
				//            ie.getInternalFrame().setIconifiable(true);
				//            JDesktopIcon icon = ie.getInternalFrame().getDesktopIcon();
				//            icon.setLocation(icon.getX(), icon.getY());
				NewJInternalFrame frameObj = (NewJInternalFrame) ie.getSource();
				if (frameObj != null && frameObj.isVisible()) {
					frameObj.setVisible(false);
				}
				System.out.println("minized");
			}
		});

		this.closable = true;
		this.addInternalFrameListener(new InternalFrameAdapter() {
			@Override
			public void internalFrameClosing(InternalFrameEvent e) {

				if (getTurnTimerObj() != null) {
					getTurnTimerObj().cancel();
					getTurnTimerObj().purge();
				}
				childRummyGlobalObj.sendBotLogOutRequest();
				return;
			}
		});

		this.setVisible(true);

		new ComponentMover().registerComponent(this);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jSeparator2 = new javax.swing.JSeparator();

		jLabel1.setText("Social Chat");

		jLabel2.setText("Dealer Chat");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jButton1.setText("Submit");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel3.setText("Current Players");

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane3.setViewportView(jList1);

		jLabel4.setText("Multiplier : ");

		jLabel5.setText("---");

		jLabel6.setText("Turn Info :-");

		jLabel7.setText("Name :");

		jLabel8.setText("---");

		jLabel9.setText("---");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(82, 82, 82)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												139, Short.MAX_VALUE)
										.addComponent(jLabel2).addGap(92, 92,
												92))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				23,
																				23,
																				23)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jButton1)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jSeparator1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												102,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																														.addComponent(
																																jTextField1,
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jScrollPane1,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																187,
																																Short.MAX_VALUE)
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jLabel4)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jLabel5,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				49,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																										.addComponent(
																												jLabel6)
																										.addGroup(
																												layout
																														.createSequentialGroup()
																														.addComponent(
																																jLabel7)
																														.addPreferredGap(
																																javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																														.addComponent(
																																jLabel9,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																142,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addComponent(
																												jSeparator2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												101,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				49,
																				49,
																				49)
																		.addComponent(
																				jLabel8)))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				65,
																				65,
																				65)
																		.addComponent(
																				jLabel3))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				185,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				53,
																				53,
																				53)
																		.addComponent(
																				jScrollPane3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				115,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(20, 20, 20)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel2)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																125,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																125,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				48,
																				48,
																				48)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel5))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jSeparator1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel9))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel8))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jScrollPane3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								136,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton1))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jSeparator2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(127, 127, 127)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField1;

	// End of variables declaration//GEN-END:variables

	private void setDinamicSize(ComponentEvent ce) {
		JInternalFrame tempFrame = (JInternalFrame) ce.getSource();
		tempFrame.setSize(new Dimension((int) tempFrame.getAlignmentX(),
				(int) tempFrame.getAlignmentY()));
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String str = jTextField1.getText();
		childRummyGlobalObj.sendUserChat(str, roomObject);
		//reqinitGlobalObj.sendUserChat(str, roomObject);
		jTextField1.setText("");
	}

	private void jButton1KeyActionPerformed(java.awt.event.KeyEvent evt) {
		String str = jTextField1.getText();
		childRummyGlobalObj.sendUserChat(str, roomObject);
		//reqinitGlobalObj.sendUserChat(str, roomObject);
		jTextField1.setText("");
	}

	public void updateString(String msg) {

		//str.append(msg);
		String previousChat = jTextArea1.getText();
		previousChat = previousChat + "\n" + msg;
		jTextArea1.setText(previousChat);

	}

	public void updateDealerChat(String dealerChat) {
		String previousChat = jTextArea2.getText();
		previousChat = previousChat + "\n" + dealerChat;
		jTextArea2.setText(previousChat);
	}

	public void updatePlayerNamesList(List<String> playerNamesList) {
		jList1.removeAll();
		DefaultListModel defaultList = new DefaultListModel();
		for (int k = 0; k < playerNamesList.size(); k++) {
			defaultList.addElement((String) playerNamesList.get(k));
		}
		jList1.setModel(defaultList);
	}

	public synchronized void startTurnTimer(int turnTimer, String playerName) {
		if (getTurnTimerObj() != null) {
			this.getTurnTimerObj().cancel();
			this.getTurnTimerObj().purge();
		}
		jLabel9.setText(playerName);
		turnTimerObj = new UserTurnTimer(this, turnTimer);
		this.setTurnTimerObj(turnTimerObj);

	}

	public synchronized void stopTurnTimer() {
		if (getTurnTimerObj() != null) {
			jLabel9.setText("---");
			getTurnTimerObj().cancel();
			getTurnTimerObj().purge();
			jLabel8.setText("---");
		}
	}

	public String getRoomName() {
		return roomName;
	}

	public void setRoomName(String roomName, String botName) {
		this.roomName = roomName;
		this.title = roomName + " $$ " + botName;
	}

	public void setMultiplier(String multiplier) {
		this.multiplier = multiplier;
		jLabel5.setText(multiplier);
	}

	public void updateTimerLabel(String time) {
		jLabel8.setText(time);
	}

	public int getBotId() {
		return botId;
	}

	public void setBotId(int botId) {
		this.botId = botId;
	}

	public Room getRoomObject() {
		return roomObject;
	}

	public void setRoomObject(Room roomObject) {
		this.roomObject = roomObject;
	}

	public RummyBot getRummyGlobalObj() {
		return rummyGlobalObj;
	}

	public void setRummyGlobalObj(RummyBot rummyGlobalObj) {
		this.rummyGlobalObj = rummyGlobalObj;
	}

	public RequestIniatiator getReqinitGlobalObj() {
		return reqinitGlobalObj;
	}

	public void setReqinitGlobalObj(RequestIniatiator reqinitGlobalObj) {
		this.reqinitGlobalObj = reqinitGlobalObj;
	}

	public ChildRummyBot getChildRummyGlobalObj() {
		return childRummyGlobalObj;
	}

	public void setChildRummyGlobalObj(ChildRummyBot childRummyGlobalObj) {
		this.childRummyGlobalObj = childRummyGlobalObj;
	}

	public UserTurnTimer getTurnTimerObj() {
		return turnTimerObj;
	}

	public void setTurnTimerObj(UserTurnTimer turnTimerObj) {
		this.turnTimerObj = turnTimerObj;
	}

}