package NewClient;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJInternalFrame.java
 *
 * Created on Aug 16, 2013, 11:48:14 AM
 */


import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

import BotLogin.RequestIniatiator;

import sfs2x.client.entities.Room;
import sfs2x.client.example.ChildRummyBot;
import sfs2x.client.example.RummyBot;

/**
 *
 * @author vaibhav
 */
public class NewJInternalFrame extends javax.swing.JInternalFrame {

	String roomName = "";
	int botId = 0;
	Room roomObject = null;
	RummyBot rummyGlobalObj = null;
	RequestIniatiator reqinitGlobalObj = null;
	ChildRummyBot childRummyGlobalObj = null;


	/** Creates new form NewJInternalFrame */
    public NewJInternalFrame() {
        initComponents();
       
        this.setResizable(true);
        //this.addInternalFrameListener(new WindowHandler(this));
        jTextArea1.setEditable(false);
        jTextArea1.setFocusable(false);
        jTextArea2.setEditable(false);
        jTextArea2.setFocusable(false);
        this.getRootPane().setDefaultButton(jButton1);
        
//        this.addComponentListener(new ComponentAdapter() {
//        public void componentResized(ComponentEvent ce)
//        {
//          
//        }
//        });
       
        iconable = true;
        this.addInternalFrameListener(new InternalFrameAdapter() {
        @Override
        public void internalFrameIconified(InternalFrameEvent ie)
        {
//            ie.getInternalFrame().setIconifiable(true);
//            JDesktopIcon icon = ie.getInternalFrame().getDesktopIcon();
//            icon.setLocation(icon.getX(), icon.getY());
        	NewJInternalFrame frameObj = (NewJInternalFrame)ie.getSource();
        	if(frameObj!=null && frameObj.isVisible())
        	{
        		frameObj.setVisible(false);
        	}
            System.out.println("minized");
        }
        });
        
        this.closable = true;
        this.addInternalFrameListener(new InternalFrameAdapter() {
        @Override
        public void internalFrameClosing(InternalFrameEvent e) {
        //e.getInternalFrame().dispose();
        childRummyGlobalObj.sendBotLogOutRequest();
        return;
        }
        });
       
        this.setVisible(true);
        
        new ComponentMover().registerComponent(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(10);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter(){
        	
        	@Override
        	public void keyPressed(KeyEvent e)
        	{
        		 if (e.getKeyCode()==KeyEvent.VK_ENTER){
        			 jButton1KeyActionPerformed(e);
        	        }
        	}
        });

        jLabel1.setText("Social Chat");

        jLabel2.setText("Dealer Chat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
    
    private void setDinamicSize(ComponentEvent ce)
    {
    	JInternalFrame tempFrame = (JInternalFrame)ce.getSource();
        tempFrame.setSize(new Dimension((int)tempFrame.getAlignmentX(),(int)tempFrame.getAlignmentY()));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	String str = jTextField1.getText();
    	childRummyGlobalObj.sendUserChat(str, roomObject);
    	//reqinitGlobalObj.sendUserChat(str, roomObject);
        jTextField1.setText("");
    	}
    private void jButton1KeyActionPerformed(java.awt.event.KeyEvent evt)
    {
    	String str = jTextField1.getText();
    	childRummyGlobalObj.sendUserChat(str, roomObject);
    	//reqinitGlobalObj.sendUserChat(str, roomObject);
        jTextField1.setText("");
    }
    	
	public void updateString(String msg) {
		
		//str.append(msg);
		String previousChat = jTextArea1.getText();
		previousChat = previousChat+"\n"+msg;
		jTextArea1.setText(previousChat);
		
	}
	
	public void updateDealerChat(String dealerChat)
	{
		String previousChat = jTextArea2.getText();
		previousChat = previousChat+"\n"+dealerChat;
		jTextArea2.setText(previousChat);
	}
    
	
	  public String getRoomName() {
			return roomName;
		}

		public void setRoomName(String roomName, String botName) {
			this.roomName = roomName;
			this.title = roomName+" $$ "+botName;
		}
		
		public int getBotId() {
			return botId;
		}

		public void setBotId(int botId) {
			this.botId = botId;
		}
		
		public Room getRoomObject() {
			return roomObject;
		}

		public void setRoomObject(Room roomObject) {
			this.roomObject = roomObject;
		}
		
		public RummyBot getRummyGlobalObj() {
			return rummyGlobalObj;
		}

		public void setRummyGlobalObj(RummyBot rummyGlobalObj) {
			this.rummyGlobalObj = rummyGlobalObj;
		}
		
		public RequestIniatiator getReqinitGlobalObj() {
			return reqinitGlobalObj;
		}

		public void setReqinitGlobalObj(RequestIniatiator reqinitGlobalObj) {
			this.reqinitGlobalObj = reqinitGlobalObj;
		}
		
		public ChildRummyBot getChildRummyGlobalObj() {
			return childRummyGlobalObj;
		}

		public void setChildRummyGlobalObj(ChildRummyBot childRummyGlobalObj) {
			this.childRummyGlobalObj = childRummyGlobalObj;
		}
//    class WindowHandler extends InternalFrameAdapter
//    {
//        public NewJInternalFrame ref;
//        
//        public WindowHandler(NewJInternalFrame ref) {
//            this.ref = ref;
//        }
//        
//        @Override
//        public void internalFrameClosing(InternalFrameEvent ie)
//        {
//            ref.dispose();
//        }
//    }
}


